"""
Pydantic schemas.
"""
from .recipe import (
    IngredientBase,
    IngredientCreate,
    IngredientResponse,
    RecipeIngredientBase,
    RecipeIngredientCreate,
    RecipeIngredientResponse,
    RecipeBase,
    RecipeCreate,
    RecipeUpdate,
    RecipeRatingUpdate,
    RecipeResponse,
    RecipeListResponse,
    ExtractedIngredient,
    ExtractedRecipe,
    ExtractionJobResponse,
    RecipeFilters,
    CategoryItem,
    CategoryGroup,
    CategoriesResponse,
    DuplicateMatchResponse,
    DuplicateCheckResponse,
    UploadWithDuplicateCheckResponse,
)
from .auth import (
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    Token,
    TokenData,
)
from .collection import (
    CollectionBase,
    CollectionCreate,
    CollectionUpdate,
    CollectionRecipeAdd,
    CollectionRecipeReorder,
    CollectionRecipeResponse,
    CollectionResponse,
    CollectionDetailResponse,
    CollectionListResponse,
    CollectionShareCreate,
    CollectionShareUpdate,
    CollectionShareResponse,
    CollectionShareListResponse,
)
from .cleanup import CleanupStatsResponse
from .category import (
    CategoryCreate,
    CategoryUpdate,
    CategoryAdminResponse,
    CategoryReorderRequest,
    CategoryDeleteResponse,
)
from .ingredient import (
    IngredientAdminCreate,
    IngredientAdminUpdate,
    IngredientAdminResponse,
    IngredientListResponse,
    IngredientDeleteResponse,
    DuplicateMatch,
    DuplicateGroup,
    DuplicateDetectionResponse,
    IngredientMergeRequest,
    IngredientMergeResponse,
)
from .user import (
    UserAdminResponse,
    UserListResponse,
    UserStatusUpdate,
    UserStatusResponse,
)
from .audit import (
    AuditLogResponse,
    AuditLogListResponse,
)

__all__ = [
    "IngredientBase",
    "IngredientCreate",
    "IngredientResponse",
    "RecipeIngredientBase",
    "RecipeIngredientCreate",
    "RecipeIngredientResponse",
    "RecipeBase",
    "RecipeCreate",
    "RecipeUpdate",
    "RecipeRatingUpdate",
    "RecipeResponse",
    "RecipeListResponse",
    "ExtractedIngredient",
    "ExtractedRecipe",
    "ExtractionJobResponse",
    "RecipeFilters",
    "CategoryItem",
    "CategoryGroup",
    "CategoriesResponse",
    "DuplicateMatchResponse",
    "DuplicateCheckResponse",
    "UploadWithDuplicateCheckResponse",
    # Auth schemas
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenData",
    # Collection schemas
    "CollectionBase",
    "CollectionCreate",
    "CollectionUpdate",
    "CollectionRecipeAdd",
    "CollectionRecipeReorder",
    "CollectionRecipeResponse",
    "CollectionResponse",
    "CollectionDetailResponse",
    "CollectionListResponse",
    "CollectionShareCreate",
    "CollectionShareUpdate",
    "CollectionShareResponse",
    "CollectionShareListResponse",
    # Cleanup schemas
    "CleanupStatsResponse",
    # Admin category schemas
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryAdminResponse",
    "CategoryReorderRequest",
    "CategoryDeleteResponse",
    # Admin ingredient schemas
    "IngredientAdminCreate",
    "IngredientAdminUpdate",
    "IngredientAdminResponse",
    "IngredientListResponse",
    "IngredientDeleteResponse",
    # Ingredient duplicate detection schemas
    "DuplicateMatch",
    "DuplicateGroup",
    "DuplicateDetectionResponse",
    # Ingredient merge schemas
    "IngredientMergeRequest",
    "IngredientMergeResponse",
    # Admin user schemas
    "UserAdminResponse",
    "UserListResponse",
    "UserStatusUpdate",
    "UserStatusResponse",
    # Audit log schemas
    "AuditLogResponse",
    "AuditLogListResponse",
]
