"""
Pydantic schemas.
"""
from .recipe import (
    IngredientBase,
    IngredientCreate,
    IngredientResponse,
    RecipeIngredientBase,
    RecipeIngredientCreate,
    RecipeIngredientResponse,
    RecipeBase,
    RecipeCreate,
    RecipeUpdate,
    RecipeRatingUpdate,
    RecipeResponse,
    RecipeListResponse,
    ExtractedIngredient,
    ExtractedRecipe,
    ExtractionJobResponse,
    RecipeFilters,
    CategoryItem,
    CategoryGroup,
    CategoriesResponse,
)
from .auth import (
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    Token,
    TokenData,
)
from .collection import (
    CollectionBase,
    CollectionCreate,
    CollectionUpdate,
    CollectionRecipeAdd,
    CollectionRecipeReorder,
    CollectionRecipeResponse,
    CollectionResponse,
    CollectionDetailResponse,
    CollectionListResponse,
)

__all__ = [
    "IngredientBase",
    "IngredientCreate",
    "IngredientResponse",
    "RecipeIngredientBase",
    "RecipeIngredientCreate",
    "RecipeIngredientResponse",
    "RecipeBase",
    "RecipeCreate",
    "RecipeUpdate",
    "RecipeRatingUpdate",
    "RecipeResponse",
    "RecipeListResponse",
    "ExtractedIngredient",
    "ExtractedRecipe",
    "ExtractionJobResponse",
    "RecipeFilters",
    "CategoryItem",
    "CategoryGroup",
    "CategoriesResponse",
    # Auth schemas
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenData",
    # Collection schemas
    "CollectionBase",
    "CollectionCreate",
    "CollectionUpdate",
    "CollectionRecipeAdd",
    "CollectionRecipeReorder",
    "CollectionRecipeResponse",
    "CollectionResponse",
    "CollectionDetailResponse",
    "CollectionListResponse",
]
